config/routes.rb
Rails.application.routes.draw do
  get 'api/news', to: 'api#news', as: 'api_news'
  get 'api/tweets_between_dates/:date1/:date2', to: 'api#tweets_between_dates', as: 'tweets_between_dates'
  post 'api/tweets', to: 'api#create_tweet'

  #scope '/api' do
   # get '/news', to: 'api#news', as: 'api_news'
  #end

  ActiveAdmin.routes(self)
  
  resources :tweets do
  post 'likes', to: 'tweets#likes'
  post 'retweet', to: 'tweets#retweet'
  end

  devise_for :users
  get 'home/index'
  get 'all_tweets', to: 'home#all_tweets', as: 'all_tweets'

  #get "users#follow"
  post 'follow/:user_id', to: 'users#follow', as: 'users_follow'

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href=" <%= root_path %>">Tuiter.fruna</a>
    <img src="/guruguru.png" alt="guruguru" class="avatar rounded-circle" style="height: 65px">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= form_tag(root_path, method: :get) do %>
              
                <%= link_to "Limpiar", root_path, :class => "btn btn-dark"%>
                <%= text_field_tag(:search, params[:search], :class => "form-control d-inline w-50") %>
                <%= submit_tag("Buscar", :class => "btn btn-info") %>
             
            <% end %>  
          </li> 
          <li class="nav-item">
            <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :get, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Registro', new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
          </li>   
        <% end %>
      </ul>
    </div>
  </div>  
</nav>

app/views/shared/_tweet_card.html.erb
<div class="col-12 border border-info p-3 mt-2 card-tweet">
        <div class="row">
            <div class="col-1">
                <%= image_tag (tweet.user.photo_url), :class => "avatar-in-tweet rounded-circle" %><br/>
                <% if user_signed_in? && current_user != tweet.user %>
                    <%= link_to (current_user.is_followed?(tweet.user) ? '<i class="fas fa-eye-slash text-info"></i> ' : '<i class="fas fa-eye text-info"></i> ').html_safe, users_follow_path(tweet.user.id), class:"", 'title' => (current_user.is_followed?(tweet.user) ? "Dejar de seguir" : "Seguir"),
                        'data-toggle' => 'tooltip',
                        'data-placement' => 'right',
                        method: :post
                    %>
                <% end %>
            </div>
            <div class="col-11">
                <span class="username"><%= tweet.user.username %> dice:</span><br/>
                <span><%= link_to '<i class="fas fa-history"></i>'.html_safe+" "+distance_of_time_in_words(Time.now, tweet.created_at), tweet %></span><br/>
                <div class="tweet-content p-3 mb-2"><%= tweet.content.html_safe %></div>
                <% if tweet.is_retweet? %>
                    <%= link_to "Retweet...", tweet.tweet_ref%>
                <%end%>
            </div>

            <div class="col-12">
                <div class="p3 text-right mb-2 tweet-options">
                    <% if user_signed_in? %>
                        <span>
                            <%= tweet.likes.count %>
                            <% if tweet.is_liked?(current_user) %>
                                <%= link_to '<i class="fas fa-thumbs-up text-info"></i>'.html_safe, tweet_likes_path(tweet), method: :post %>
                            <% else %>
                                <%= link_to '<i class="far fa-thumbs-up text-muted"></i>'.html_safe, tweet_likes_path(tweet), method: :post %>
                            <% end %>
                        </span>
                        |
                        <span>
                            <%= tweet.count_rt %>
                            <% if tweet.count_rt > 0 %>
                                <%= link_to '<i class="fas fa-retweet text-info"></i>'.html_safe, tweet_retweet_path(tweet), method: :post%>
                            <% else %>
                                <%= link_to '<i class="fas fa-retweet text-muted"></i>'.html_safe, tweet_retweet_path(tweet), method: :post%>
                            <% end %>
                        </span>
                    <% end %>
                </div>
            </div>
        </div>
    </div>